X-common:
  any_place_where_a_key_is: &any_place_where_a_key_is /(?:thumb|main)_.*/gi
  main_key_main_except_top: &main_key_main_except_top /^main_(?!.*top).*$/gi
  main_key_main_except_bottom: &main_key_main_except_bottom /^main_(?!.*bottom).*$/gi
  any_key_expect_the_outer_ones: &any_key_expect_the_outer_ones /(?:^main_(?!pinky)|^thumb_(?!.*inner)).*$/gi

units:
  # Proxy Spacing Variables
  kx: cx
  ky: cy
  # Padding Variables
  px: kx + 4
  py: ky + 4
  # Double Padding Variables
  dpx: kx + 8
  dpy: ky + 8
  # Defaults to M2 Screws
  screwSize: 1.5
  standoffSize: 2.5

points:
    rotate: 7
    key.padding: ky
    zones:
        main:
            anchor:
                shift: [100, -100]
            rows:
                bottom.row_net: P4
                home.row_net: P0
                top.row_net: P1
            columns:
                pinky:
                    key:
                        col_net: P9
                        spread: kx
                    rows:
                        bottom:
                        home:
                        top:
                ring:
                    key:
                        col_net: P8
                        origin: [-12, -19]
                        stagger: 4
                        splay: -7
                        spread: kx
                    rows:
                        bottom:
                        home:
                        top:
                middle:
                    key:
                        col_net: P7
                        stagger: 2.5
                        spread: kx
                    rows:
                        bottom:
                        home:
                        top:
                index:
                    key:
                        col_net: P6
                        stagger: -2.5
                        spread: kx
                    rows:
                        bottom:
                        home:
                        top:
                inner:
                    key:
                        col_net: P5
                        stagger: -2.5
                        spread: kx
                    rows:
                        bottom:
                        home:
                        top:
        thumb:
            anchor:
                ref: main_inner_bottom
                shift: [-1.2kx, -1.5ky]
            rows.home.row_net: P10
            columns:
                inner.key:
                    col_net: P7
                    spread: kx
                    splay: -5
                home.key:
                    col_net: P6
                    spread: kx + 2
                    rotate: -18
                    stagger: -3.2
                outer.key:
                    col_net: P5
                    spread: kx
                    rotate: -36
                    stagger: -9.2
outlines:
    _board_outline:
        - what: polygon
          fillet: 2
          points:
              - ref: thumb_outer_home
                shift: [0.5px, 0.5py]
              - ref: thumb_outer_home
                shift: [0.5px, -0.5py]
              - ref: thumb_outer_home
                shift: [-0.4px, -0.5py]

              - ref: thumb_home_home
                shift: [0.3px, -0.5py]
              - ref: thumb_home_home
                shift: [-0.4px, -0.5py]

              - ref: thumb_inner_home
                shift: [0.3px, -0.5py]
              - ref: thumb_inner_home
                shift: [-0.5px, -0.5py]

              - ref: main_pinky_bottom
                shift: [1.6px, -0.5py]
              - ref: main_pinky_bottom
                shift: [0.5px, -0.5py]
              - ref: main_pinky_bottom
                shift: [-0.5px, -0.5py]

              - ref: main_pinky_top
                shift: [-0.5px, 0.5py]
              - ref: main_pinky_top
                shift: [0.5px, 0.5py]

              - ref: main_ring_top
                shift: [-0.4px, 0.5py]
              - ref: main_ring_top
                shift: [0.35px, 0.5py]

              - ref: main_middle_top
                shift: [-0.3px, 0.51py]
              - ref: main_middle_top
                shift: [0.3px, 0.51py]

              - ref: main_index_top
                shift: [-0.3px, 0.5py]
              - ref: main_index_top
                shift: [0.3px, 0.5py]

              - ref: main_inner_top
                shift: [-0.3px, 0.5py]
              - ref: main_inner_top
                shift: [0.3px, 0.5py]

              - ref: main_inner_top
                shift: [0.5px, 0.4py]
              - ref: main_inner_top
                shift: [1.55px, 0.4py]

              - ref: main_inner_bottom
                shift: [1.55px, -0.4py]
    _xlboard_outline:
        - what: polygon
          fillet: 2
          operation: stack
          points:
              - ref: thumb_outer_home
                shift: [0.5dpx, 0.5dpy]
              - ref: thumb_outer_home
                shift: [0.5dpx, -0.5dpy]
              - ref: thumb_outer_home
                shift: [-0.4dpx, -0.5dpy]

              - ref: thumb_home_home
                shift: [0.3dpx, -0.5dpy]
              - ref: thumb_home_home
                shift: [-0.4dpx, -0.5dpy]

              - ref: thumb_inner_home
                shift: [0.3dpx, -0.5dpy]
              - ref: thumb_inner_home
                shift: [-0.5dpx, -0.5dpy]

              - ref: main_pinky_bottom
                shift: [1.6dpx, -0.5dpy]
              - ref: main_pinky_bottom
                shift: [0.5dpx, -0.5dpy]
              - ref: main_pinky_bottom
                shift: [-0.5dpx, -0.5dpy]

              - ref: main_pinky_top
                shift: [-0.5dpx, 0.5dpy]
              - ref: main_pinky_top
                shift: [0.5dpx, 0.5dpy]

              - ref: main_ring_top
                shift: [-0.4dpx, 0.5dpy]
              - ref: main_ring_top
                shift: [0.35dpx, 0.5dpy]

              - ref: main_middle_top
                shift: [-0.3dpx, 0.51dpy]
              - ref: main_middle_top
                shift: [0.3dpx, 0.51dpy]

              - ref: main_index_top
                shift: [-0.3dpx, 0.5dpy]
              - ref: main_index_top
                shift: [0.3dpx, 0.5dpy]

              - ref: main_inner_top
                shift: [-0.3dpx, 0.5dpy]
              - ref: main_inner_top
                shift: [0.3dpx, 0.5dpy]

              - ref: main_inner_top
                shift: [0.5dpx, 0.4dpy]
              - ref: main_inner_top
                shift: [1.55dpx, 0.4dpy]

              - ref: main_inner_bottom
                shift: [1.55dpx, -0.4dpy]
    _keycap_outlines:
        - what: rectangle
          fillet: 2
          where: true
          size: [1kx - 0.5, 1ky - 0.5] # Choc keycaps are 17.5 x 16.5
    preview:
        - what: outline
          name: _board_outline
          operation: stack
        - what: outline
          name: _keycap_outlines
          operation: stack
pcbs.ergonator:
    outlines:
        main.outline: _board_outline
        keycaps:
            outline: _keycap_outlines
            layer: Eco1.User
    footprints:
        choc-hotswap:
            what: choc
            where: *any_place_where_a_key_is
            params:
                keycaps: true
                hotswap: true
                reverse: true
                from: "{{col_net}}"
                to: "{{name}}"
        choc-non-hotswap:
            what: choc
            where: *any_place_where_a_key_is
            params:
                keycaps: true
                hotswap: false
                reverse: true
                from: "{{col_net}}"
                to: "{{name}}"
            adjust:
                rotate: 180
        via-top:
            what: via
            where: *any_place_where_a_key_is
            params:
                net: "{{name}}"
            adjust:
                shift:
                    - &via-top-shift-x 0
                    - &via-top-shift-y -3.5
        via-middle:
            what: via
            where: *any_place_where_a_key_is
            params:
                net: "{{col_net}}"
            adjust:
                shift:
                    - &via-middle-shift-x 0
                    - &via-middle-shift-y 3.5
        via-bottom:
            what: via
            where: *any_key_expect_the_outer_ones
            params:
                net: "{{row_net}}"
            adjust:
                shift:
                    - &via-bottom-shift-x 0
                    - &via-bottom-shift-y -8.5
        diode:
            what: sod-123w
            where: *any_place_where_a_key_is
            params:
                from: "{{name}}"
                to: "{{row_net}}"
            adjust:
                shift: [4.8, -7]
                rotate: 180
        route-from-top-via-to-higher-frond-pad:
            what: route
            where: *any_place_where_a_key_is
            params:
                side: &route-back B
                net: "{{name}}"
                points:
                    - start: { x: *via-top-shift-x, y: *via-top-shift-y }
                      end:
                          x: &route-from-top-via-to-higher-pad-stop-1-x-frond -1
                          y: &route-from-top-via-to-higher-pad-stop-1-y -4
                    - start:
                          x: *route-from-top-via-to-higher-pad-stop-1-x-frond
                          y: *route-from-top-via-to-higher-pad-stop-1-y
                      end:
                          y: &route-from-top-via-to-higher-pad-stop-2-y -6
                          x: &route-from-top-via-to-higher-pad-stop-2-x-left -3
                    - start:
                          x: *route-from-top-via-to-higher-pad-stop-1-x-frond
                          y: *route-from-top-via-to-higher-pad-stop-1-y
                      end:
                          x: &route-from-top-via-to-higher-pad-stop-3-x-left -5
                          y: &route-from-top-via-to-higher-pad-stop-3-y 4
        route-from-top-via-to-higher-back-pad:
            what: route
            where: *any_place_where_a_key_is
            params:
                side: &route-frond F
                net: "{{name}}"
                points:
                    - start: { x: *via-top-shift-x, y: *via-top-shift-y }
                      end:
                          x: &route-from-top-via-to-higher-pad-stop-1-x-back 1
                          y: *route-from-top-via-to-higher-pad-stop-1-y
                    - start:
                          x: *route-from-top-via-to-higher-pad-stop-1-x-back
                          y: *route-from-top-via-to-higher-pad-stop-1-y
                      end:
                          y: *route-from-top-via-to-higher-pad-stop-2-y
                          x: &route-from-top-via-to-higher-pad-stop-2-x-right 3
                    - start:
                          x: *route-from-top-via-to-higher-pad-stop-1-x-back
                          y: *route-from-top-via-to-higher-pad-stop-1-y
                      end:
                          x: &route-from-top-via-to-higher-pad-stop-3-x-right 5
                          y: *route-from-top-via-to-higher-pad-stop-3-y
        route-from-middle-via-to-lower-frond-pad:
            what: route
            where: *any_place_where_a_key_is
            params:
                side: *route-frond
                net: "{{col_net}}"
                points:
                    - start: { x: *via-middle-shift-x, y: *via-middle-shift-y }
                      end:
                          x: &route-from-middle-via-to-lower-pad-stop-1-x-frond -5
                          y: &route-from-middle-via-to-lower-pad-stop-1-y -1.5
                    - start:
                          x: *route-from-middle-via-to-lower-pad-stop-1-x-frond
                          y: *route-from-middle-via-to-lower-pad-stop-1-y
                      end:
                          x: &route-from-middle-via-to-lower-pad-stop-2-x-frond -7
                          y: &route-from-middle-via-to-lower-pad-stop-2-y -1.5
                    - start:
                          x: *route-from-middle-via-to-lower-pad-stop-2-x-frond
                          y: *route-from-middle-via-to-lower-pad-stop-2-y
                      end:
                          y: &route-from-middle-via-to-lower-pad-stop-3-y -4
                          x: -8.1
        route-from-middle-via-to-lower-back-pad:
            what: route
            where: *any_place_where_a_key_is
            params:
                side: *route-back
                net: "{{col_net}}"
                points:
                    - start: { x: *via-middle-shift-x, y: *via-middle-shift-y }
                      end:
                          x: &route-from-middle-via-to-lower-pad-stop-1-x-back 5
                          y: *route-from-middle-via-to-lower-pad-stop-1-y
                    - start:
                          x: *route-from-middle-via-to-lower-pad-stop-1-x-back
                          y: *route-from-middle-via-to-lower-pad-stop-1-y
                      end:
                          x: &route-from-middle-via-to-lower-pad-stop-2-x-back 7
                          y: *route-from-middle-via-to-lower-pad-stop-2-y
                    - start:
                          x: *route-from-middle-via-to-lower-pad-stop-2-x-back
                          y: *route-from-middle-via-to-lower-pad-stop-2-y
                      end:
                          y: *route-from-middle-via-to-lower-pad-stop-3-y
                          x: 8.1
        route-from-middle-via-to-lower-hole:
            what: route
            where: *any_place_where_a_key_is
            params:
                side: *route-back
                net: "{{col_net}}"
                points:
                    - start: { x: *via-middle-shift-x, y: *via-middle-shift-y }
                      end:
                          x: &lower-hole-x 0
                          y: &lower-hole-y 6
                    - start: { x: *lower-hole-x, y: *lower-hole-y }
                      end: { y: 7, x: 3.25 }
        route-from-edge-to-bottom-via:
            what: route
            where: *any_key_expect_the_outer_ones
            params:
                side: *route-frond
                net: "{{row_net}}"
                points:
                    - start: { y: &lower-via-route-start-y 8.5, x: -7.5 }
                      end: { y: *lower-via-route-start-y, x: *via-bottom-shift-x }
        route-from-bottom-via-to-diode:
            what: route
            where: *any_key_expect_the_outer_ones
            params:
                side: *route-back
                net: "{{row_net}}"
                points:
                    - start:
                          x: *via-bottom-shift-x
                          y: *lower-via-route-start-y
                      end:
                          x: &to-lower-diode-stop-1-x 6.25
                          y: *lower-via-route-start-y
                    - start:
                          x: *to-lower-diode-stop-1-x
                          y: *lower-via-route-start-y
                      end:
                          x: *to-lower-diode-stop-1-x
                          y: 7
        route-from-higher-back-pad-to-upper-key:
            what: route
            where: *main_key_main_except_top
            params:
                side: *route-back
                net: "{{name}}"
                points:
                    - start:
                          y: *route-from-top-via-to-higher-pad-stop-2-y
                          x: *route-from-top-via-to-higher-pad-stop-2-x-left
                      end:
                          y: -8.5
                          x: &route-to-neighboring-key-x-left -4.7
        route-from-higher-hole-pad-to-lower-key-left:
            what: route
            where: *main_key_main_except_bottom
            params:
                side: *route-back
                net: "{{name}}"
                points:
                    - start:
                          x: *route-from-top-via-to-higher-pad-stop-3-x-left
                          y: *route-from-top-via-to-higher-pad-stop-3-y
                      end:
                          x: *route-to-neighboring-key-x-left
                          y:  8.5
        promicro:
            what: promicro_pretty
            where:
                ref: main_inner_home
            adjust:
                shift: [22, 6.5]
                rotate: -90
        reset_switch: # Reset Switch
            what: wuerth-434121025816
            where:
                ref: main_inner_bottom
                shift: [25, -6]
                rotate: 0
            params:
                r1: RST
                r2: GND
        front_text: &text
            what: text
            where: &textWhere
                ref: main_inner_bottom
                shift: [31, -25]
                rotate: 82
            params: &textParams
                text: ERGONATOR[v1.0]
        back_text:
            <<: *text
            params:
                <<: *textParams
                layer: B.SilkS
                justify: mirror
        safeText:
            <<: *text
            what: keepout
            params:
                points:
                    - x: -0.5
                      y: -2
                    - x: 15.5
                      y: -2
                    - x: 15.5
                      y: 2
                    - x: -0.5
                      y: 2
        connector: # TRRS Connector
            what: trrs
            params:
                reverse: true
                A: VCC
                B: P2
                C: P3
                D: GND
            where:
                ref: main_inner_bottom
                shift: [30, 0]
                rotate: -90
        hand_front: &icon
            what: hand_front
            where:
                ref: main_inner_bottom
                shift: [13, -11]
                rotate: -8
            params:
                scale: 0.02
        hand_back:
            <<: *icon
            what: hand_back
        icon:
            <<: *icon
            what: keepout
            params:
                points:
                    -   x: -0.5
                        y: -0.5
                    -   x: 13.25
                        y: -0.5
                    -   x: 13.25
                        y: 13.25
                    -   x: -0.5
                        y: 13.25
        holeTopLeft:
          what: mountinghole
          where:
            ref: main_pinky_top
            shift: [12, 0]
        holeBottomLeft:
          what: mountinghole
          where:
            ref: main_pinky_bottom
            shift: [10, -1]
        holeTopRight:
          what: mountinghole
          where:
            ref: main_inner_top
            shift: [10, -3]
        holeBottomRight:
          what: mountinghole
          where:
            ref: thumb_home_home
            shift: [2, 15]
cases:
    bottom:
        -   name: _board_outline
            extrude: 1
    xlBottom:
        -   name: _xlboard_outline
            extrude: 1
    _outerWall:
        -   name: _xlboard_outline
            extrude: 4
    _innerWall:
        -   name: _board_outline
            extrude: 4
    wall:
        -   what: case
            name: _outerWall
            operation: add
        -   what: case
            name: _innerWall
            operation: subtract


