units:
  dcx: px
  dcy: py
  px: px + 4
  py: py + 4
points:
  rotate: 7
  key.padding: py
  zones:
    main:
      anchor:
        shift:
        - 100
        - -100
      rows:
        bottom.row_net: P4
        home.row_net: P0
        top.row_net: P1
      columns:
        pinky:
          key:
            col_net: P9
            spread: px
          rows:
            bottom: null
            home: null
            top: null
        ring:
          key:
            col_net: P8
            origin:
            - -12
            - -19
            stagger: 4
            splay: -7
            spread: px
          rows:
            bottom: null
            home: null
            top: null
        middle:
          key:
            col_net: P7
            stagger: 2.5
            spread: px
          rows:
            bottom: null
            home: null
            top: null
        index:
          key:
            col_net: P6
            stagger: -2.5
            spread: px
          rows:
            bottom: null
            home: null
            top: null
        inner:
          key:
            col_net: P5
            stagger: -2.5
            spread: px
          rows:
            bottom: null
            home: null
            top: null
    thumb:
      anchor:
        ref: main_inner_bottom
        shift:
        - -1.2px
        - -1.5py
      rows.home.row_net: P10
      columns:
        inner.key:
          col_net: P7
          spread: px
          splay: -5
        home.key:
          col_net: P6
          spread: px + 2
          rotate: -18
          stagger: -3.2
        outer.key:
          col_net: P5
          spread: px
          rotate: -36
          stagger: -9.2
outlines:
  _board_outline:
  - what: polygon
    fillet: 2
    points:
    - ref: thumb_outer_home
      shift:
      - 0.6px
      - 0.6py
    - ref: thumb_outer_home
      shift:
      - 0.6px
      - -0.6py
    - ref: thumb_outer_home
      shift:
      - -0.4px
      - -0.6py
    - ref: thumb_home_home
      shift:
      - 0.4px
      - -0.6py
    - ref: thumb_home_home
      shift:
      - -0.4px
      - -0.6py
    - ref: thumb_inner_home
      shift:
      - 0.4px
      - -0.6py
    - ref: thumb_inner_home
      shift:
      - -0.6px
      - -0.6py
    - ref: main_pinky_bottom
      shift:
      - 1.6px
      - -0.6py
    - ref: main_pinky_bottom
      shift:
      - 0.6px
      - -0.6py
    - ref: main_pinky_bottom
      shift:
      - -0.6px
      - -0.6py
    - ref: main_pinky_top
      shift:
      - -0.6px
      - 0.6py
    - ref: main_pinky_top
      shift:
      - 0.4px
      - 0.6py
    - ref: main_ring_top
      shift:
      - -0.5px
      - 0.6py
    - ref: main_ring_top
      shift:
      - 0.4px
      - 0.6py
    - ref: main_middle_top
      shift:
      - -0.4px
      - 0.61py
    - ref: main_middle_top
      shift:
      - 0.4px
      - 0.6py
    - ref: main_index_top
      shift:
      - -0.4px
      - 0.6py
    - ref: main_index_top
      shift:
      - 0.5px
      - 0.6py
    - ref: main_inner_top
      shift:
      - -0.4px
      - 0.6py
    - ref: main_inner_top
      shift:
      - 0.5px
      - 0.6py
    - ref: main_inner_top
      shift:
      - 0.6px
      - 0.5py
    - ref: main_inner_top
      shift:
      - 1.9px
      - 0.5py
    - ref: main_inner_bottom
      shift:
      - 1.9px
      - -0.6py
  _keycap_outlines:
  - what: rectangle
    fillet: 2
    where: true
    size:
    - 1px - 0.5
    - 1py - 0.5
  preview:
  - what: outline
    name: _board_outline
    operation: stack
  - what: outline
    name: _keycap_outlines
    operation: stack
pcbs.ergonator:
  outlines:
    main.outline: _board_outline
    keycaps:
      outline: _keycap_outlines
      layer: Eco1.User
  footprints:
    diode:
      what: sod-123w
      where: true
      params:
        from: '{{name}}'
        to: '{{row_net}}'
      adjust:
        shift:
        - 0
        - -7.0
        rotate: 0
    choc:
      what: choc
      where: true
      params:
        keycaps: true
        hotswap: true
        reverse: true
        from: '{{col_net}}'
        to: '{{name}}'
    promicro:
      what: promicro_pretty
      where:
        ref: main_inner_home
      adjust:
        shift:
        - 22
        - 6.5
        rotate: -90
    reset_switch:
      what: wuerth-434121025816
      where:
        ref: main_inner_bottom
        shift:
        - 25
        - -6
        rotate: 0
      params:
        r1: RST
        r2: GND
    front_text:
      what: text
      where:
        ref: main_inner_bottom
        shift:
        - 31
        - -25
        rotate: 82
      params:
        text: ERGONATOR[v1.0]
    back_text:
      what: text
      where:
        ref: main_inner_bottom
        shift:
        - 31
        - -25
        rotate: 82
      params:
        text: ERGONATOR[v1.0]
        layer: B.SilkS
        justify: mirror
    safeText:
      what: keepout
      where:
        ref: main_inner_bottom
        shift:
        - 31
        - -25
        rotate: 82
      params:
        points:
        - x: -0.5
          y: -2
        - x: 15.5
          y: -2
        - x: 15.5
          y: 2
        - x: -0.5
          y: 2
    connector:
      what: trrs
      params:
        reverse: true
        A: VCC
        B: P2
        C: P3
        D: GND
      where:
        ref: main_inner_bottom
        shift:
        - 30
        - 0
        rotate: -90
    hand_front:
      what: hand_front
      where:
        ref: main_inner_bottom
        shift:
        - 13
        - -11
        rotate: -8
      params:
        scale: 0.02
    hand_back:
      what: hand_back
      where:
        ref: main_inner_bottom
        shift:
        - 13
        - -11
        rotate: -8
      params:
        scale: 0.02
    icon:
      what: keepout
      where:
        ref: main_inner_bottom
        shift:
        - 13
        - -11
        rotate: -8
      params:
        points:
        - x: -0.5
          y: -0.5
        - x: 13.25
          y: -0.5
        - x: 13.25
          y: 13.25
        - x: -0.5
          y: 13.25
    holeTopLeft:
      what: mountinghole
      where:
        ref: main_pinky_top
        shift:
        - 12
        - 0
    holeBottomLeft:
      what: mountinghole
      where:
        ref: main_pinky_bottom
        shift:
        - 10
        - -1
    holeTopRight:
      what: mountinghole
      where:
        ref: main_inner_top
        shift:
        - 10
        - -3
    holeBottomRight:
      what: mountinghole
      where:
        ref: thumb_home_home
        shift:
        - 2
        - 15
cases:
  bottom:
  - name: _board_outline
    extrude: 1
